spring:
  application:
    name: hairbookingapp
  datasource:
    url: "jdbc:mysql://localhost:3306/hairsalonapp"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: datvmse184665@fpt.edu.vn
    password: zrkyqtczgqblaqpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: 8080

app:
  jwtSecret: "QcyGTY2KSEVAfx94cmzNhjJToOCnc9GYmHFdZfe2Yuy0z1oyJuQWsoeLZgEZtPdzdKmibPfJ81DUk4fKUm0uSsnxnRUpVNtFcr3DlxPyRyrBhs4w6gypdwffctXE4BXxz5jZJuFwspuupXJDKQdJJxuFb0JtBj3Idekx5g8DCSleNw4AlIv7KWZ9NwRs0p1ythOlHZd0Z75L1GdBuGlorYgThsvfCTgGhpMsiObpGKnDOZgrtIPgPJTAyPRAskWNpXmErNfeY0z4OQOOoALziKphsQrTrrtuI9SjPHTZfcREFLPprurVkMK1trPmvGL8Wd2oNFin9ydavJLLCpJvXaP6qAQk3MLe3pTwyERDpRrSudLsuCghYcjlKor639RRkAh37y51nj667nY5B1d6aIHiP86fIyrblUz10ovuFS2xmQZLcVr8Kj9wUnVvTANAmNmk2gZ8gGiEQ8IP0zVD32TI95d0AkX6B2nRp4uhh3mj6yawq2T8vd7k0VyAesMN
"
  comboPercent: 20
